### ISSUE TITLE
[Feature Request] Add support for TLS

### ISSUE THREAD

**Issue by micah686** [FredTheBarber/VndbClient#1]
Could you add support for TLS in your client, since the VNDB API just got support for it?
https://vndb.org/t3599/3#68

**Comment by FredTheBarber** [comment]
Sure thing, thanks for the heads-up. I'll try to get to it tonight or tomorrow.

**Comment by FredTheBarber** [comment]
Done. Added optional username/password login as well, since the only reason I wasn't doing that was lack of TLS.
