### ISSUE TITLE
[Bug/Help Wanted] The Local Security Authority cannot be contacted

### ISSUE THREAD

**Issue by Onkelsam** [FredTheBarber/VndbClient#2]
I used your Client in my [program ](https://github.com/Onkelsam/VNDBUpdater) (slightly modified). Now, one of the users of my program has a bug at "sslStream.AuthenticateAsClient":

Exception: AuthenticationException
Message: A call to SSPI failed, see inner exception.
Inner Exception: Win32Exception
Inner Exception Message: The Local Security Authority cannot be contacted.

I already searched for solutions and didn't find anything that applied. Maybe you encountered this problem before and have an idea how to solve it. The exception only appears with one user using Windows 7 64bit and having .Net 4.5 installed.

Thanks.

**Comment by FredTheBarber** [comment]
Wow, that's a pretty interesting error. So, the .Net API it calls to do SSL is internally wrapping calls to the Win32 SChannel library (the built-in Windows SSL library), one of which is returning SEC_E_INTERNAL_ERROR. That's by far most likely coming from either a call to 
AcquireCredentialsHandle() - https://msdn.microsoft.com/en-us/library/windows/desktop/aa374716(v=vs.85).aspx
InitializeSecurityContext() - https://msdn.microsoft.com/en-us/library/windows/desktop/aa375924(v=vs.85).aspx
Unfortunately, the documentation doesn't really tell you much for that error on those APIs, and oddly I've never seen that error before on an SChannel call, at least that I can remember. Maybe something very, very strange going on with that user's machine, like a really invasive virus? 

At any rate, for the next next step in debugging, I'd check the Windows Event Log for any errors reported by SChannel. IIRC, the right place to look would be:
Event Viewer -> Windows Logs -> Application
They'd probably appear at the top with an "Error" icon and Source listed as "SChannel". None on my machine, so I can't confirm, unfortunately (or perhaps fortunately for me...).

Good luck!

**Comment by Onkelsam** [comment]
Thank you very much Fred. I hope I didn't steal too much of your time :).

I sent your info to the user. Hopefully he'll have the patience to check it out.
